import { TBot, TTradeLog } from './types';

export const MOCK_BOTS: TBot[] = [
    {
        id: 'bot-001',
        name: 'Trend Rider Pro',
        strategy: 'Trend Following',
        market: 'Volatility 75',
        risk: 'Medium',
        winRate: 68,
        status: 'Active',
        description: 'Rides market trends using EMA crossover with RSI confirmation. Best on trending markets.',
        author: 'Duke',
        rating: 4.8,
        trades: 1240,
        profit: 23.4,
        tags: ['EMA', 'RSI', 'Trend'],
    },
    {
        id: 'bot-002',
        name: 'Even Odd Sniper',
        strategy: 'Even / Odd',
        market: 'Volatility 100',
        risk: 'Low',
        winRate: 72,
        status: 'Active',
        description: 'Snipes even/odd digit patterns using statistical analysis with martingale recovery.',
        author: 'Duke',
        rating: 4.5,
        trades: 3420,
        profit: 18.2,
        tags: ['Digits', 'Statistical'],
    },
    {
        id: 'bot-003',
        name: 'Boom Hunter',
        strategy: 'Spike Detector',
        market: 'Boom 1000',
        risk: 'High',
        winRate: 61,
        status: 'Testing',
        description: 'Detects boom spike patterns and enters at the right moment. High reward, high risk.',
        author: 'Duke',
        rating: 4.2,
        trades: 540,
        profit: 41.7,
        tags: ['Spikes', 'Boom', 'High Risk'],
    },
    {
        id: 'bot-004',
        name: 'Crash Scalper',
        strategy: 'Scalping',
        market: 'Crash 500',
        risk: 'High',
        winRate: 59,
        status: 'Testing',
        description: 'Scalps micro-moves on Crash 500 before spike events. Fast execution required.',
        author: 'Duke',
        rating: 3.9,
        trades: 820,
        profit: 35.1,
        tags: ['Scalp', 'Crash', 'Fast'],
    },
    {
        id: 'bot-005',
        name: 'Over Under Oracle',
        strategy: 'Over / Under',
        market: 'Volatility 25',
        risk: 'Low',
        winRate: 74,
        status: 'Active',
        description: 'Predicts over/under digits on low-volatility indices. Very consistent win rate.',
        author: 'Duke',
        rating: 4.7,
        trades: 2100,
        profit: 12.9,
        tags: ['Digits', 'Low Risk', 'Consistent'],
    },
    {
        id: 'bot-006',
        name: 'Range Breaker',
        strategy: 'Breakout',
        market: 'Volatility 50',
        risk: 'Medium',
        winRate: 65,
        status: 'Beta',
        description: 'Identifies consolidation zones and trades breakouts with smart stop management.',
        author: 'Duke',
        rating: 4.1,
        trades: 310,
        profit: 28.6,
        tags: ['Breakout', 'Range', 'Smart SL'],
    },
];

export const MOCK_TRADE_LOGS: TTradeLog[] = [
    { id: 'l1', time: '14:32:01', contract: 'Rise', stake: 1.5, result: 'Win', profit: 1.35 },
    { id: 'l2', time: '14:32:18', contract: 'Fall', stake: 1.5, result: 'Loss', profit: -1.5 },
    { id: 'l3', time: '14:32:35', contract: 'Rise', stake: 3.0, result: 'Win', profit: 2.7 },
    { id: 'l4', time: '14:32:52', contract: 'Rise', stake: 3.0, result: 'Win', profit: 2.7 },
    { id: 'l5', time: '14:33:10', contract: 'Fall', stake: 1.5, result: 'Win', profit: 1.35 },
];
